model:
  arch: sl_gcn
  pretrained: experiments/sl_gcn_vsl400
  num_points: 27
  groups: 8
  block_size: 41
  in_channels: 3
  num_frozen_layers: 0
  num_frames: 150
inference:
  source: webcam
  output_dir: demo/sl_gcn_webcam
  use_onnx: False
  device: cpu
  show_skeleton: True
  visualize: True
  top_k: 3
